### ISSUE TITLE
Flexbox layout

### ISSUE THREAD

**Issue by domoritz** [uwdb/website#9]
Please use flexbox for the logos on the front page. Also, include from another file so that we can use markdown.

**Comment by domoritz** [comment]
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by BrandonHaynes** [comment]
I'll be closely mirroring the homepage layout on the project page, so if I can reuse the included list (and CSS) that would be fantastic.

**Comment by domoritz** [comment]
I was talking about the logo list, not the projects list. So you can probably reuse the CSS but not the list itself. I think by "layout" you meant just the general way to do it, but just to make sure that there is no confusion. 

I think flexbox is really useful for the logos on the front page, the projects list, and the photos on the peoples page (cc @jingjingwang). 

![screen shot 2015-03-10 at 11 06 27](https://cloud.githubusercontent.com/assets/589034/6581652/a9e5b412-c715-11e4-9e31-5c8a67b63594.png)

**Comment by domoritz** [comment]
The css will probably be something like

``` css
.flexcontainer {
   display: flex;
   align-items: center;
   justify-content: center;
   flex-direction: row;
   flex-wrap: wrap;
   flex-flow: row wrap;
   align-content: flex-end;
}
```
